steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/diet-agent:latest', '-f', 'Dockerfile.agent', '.']
    timeout: '3600s'  # 1 hour timeout for build
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/diet-agent:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'diet-agent'
      - '--image'
      - 'gcr.io/$PROJECT_ID/diet-agent:latest'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      # No secrets configuration - using .env file instead

# Set a longer timeout for the entire build
timeout: '3600s'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/diet-agent:latest'