steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nutribot-streamlit:latest', '-f', 'Dockerfile.streamlit', '.']
    timeout: '1800s'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nutribot-streamlit:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nutribot-streamlit'
      - '--image'
      - 'gcr.io/$PROJECT_ID/nutribot-streamlit:latest'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
  
images:
  - 'gcr.io/$PROJECT_ID/nutribot-streamlit:latest'
timeout: '1800s'